spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Account
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Options: validate, update, create, create-drop
    show-sql: true # Enable to see SQL queries in logs
    properties:
      hibernate:
        format_sql: true # Pretty print SQL in logs
  sql:
    init:
      mode: always # Initializes the database schema if necessary

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    client:
      registerWithEureka: true
      fetchRegistry: true
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 8083

info:
  app:
    name: ACCOUNT-SERVICE
    description: "Account Service application"
    version: "1.0.0"
